run:
  timeout: 2m

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - reflectvaluecompare # can be enabled in the future
  gocyclo:
    min-complexity: 40 # 30 by default (but we recommend 10-20)
  goconst:
    min-len: 3
    min-occurrences: 3
  gomoddirectives:
    replace-allow-list:
      - github.com/imdario/mergo
  misspell:
    locale: US
  mnd:
    # List of enabled checks, see https://github.com/tommy-muehle/go-mnd/#checks for description.
    checks:
      - case
      - condition
      - operation
      - return
      - assign
  funlen:
    lines: -1
    statements: 80 # default 40
  gocognit:
    min-complexity: 65 # default 30
  gofumpt:
    extra-rules: true
  godox:
    keywords:
      - FIXME

linters:
  enable-all: true
  disable:
    - execinquery # Deprecated
    - gomnd # Deprecated
    - cyclop # duplicate of gocyclo
    - rowserrcheck # SQL
    - sqlclosecheck # SQL
    - dupl
    - lll
    - nestif
    - err113
    - wrapcheck
    - nlreturn
    - wsl
    - exhaustive
    - exhaustruct
    - tparallel
    - testpackage
    - paralleltest
    - forcetypeassert
    - varnamelen

issues:
  exclude-use-default: false
  max-same-issues: 0
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
    - 'package-comments: should have a package comment'
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
        - goconst
        - gosec
        - maintidx
    - path: 'parser/element_fill.go'
      linters:
        - mnd
